# Generated by Django 6.1.1 on 2026-09-21 22:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mensagens_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagens',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagem'),
        ),
    ]
